name: Release

on:
  push:
    tags:
      - v*.*.*
    branches-ignore:
      - '**'

env:
  IMAGE_NAME: diesel

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Login GitHub Registry
        run: docker login docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build Image
        run: docker build -t docker.pkg.github.com/mazrean/docker-diesel/${IMAGE_NAME}:${IMAGE_TAG}-mysql .
      - name: Push image to GitHub Registry
        run: docker push docker.pkg.github.com/mazrean/docker-diesel/${IMAGE_NAME}:${IMAGE_TAG}-mysql
      - name: Push image to GitHub Registry (latest)
        run: |
          docker tag docker.pkg.github.com/mazrean/docker-diesel/${IMAGE_NAME}-mysql:$IMAGE_TAG docker.pkg.github.com/mazrean/docker-diesel/${IMAGE_NAME}-mysql:latest
          docker push docker.pkg.github.com/mazrean/docker-diesel/${IMAGE_NAME}-mysql:latest