name: Release

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: diesel

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG env
        run: echo "IMAGE_TAG=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: asia-northeast1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ARTIFACT_REPOSITORY_KEY }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            asia-northeast1-docker.pkg.dev/cpctf-338715/system/docker-diesel:latest
            asia-northeast1-docker.pkg.dev/cpctf-338715/system/docker-diesel:${{env.TAG}}